<a href="https://colab.research.google.com/github/deveveryday/dsai_labda/blob/main/labda_python_sqlite_lesson_220926_%5BParaEntregar%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercícios de Python e SQLite

#**Exercícios de Python e SQLite**

#Parte 1: Configuração e Criação do Banco de Dados
Criação do banco de dados e conexão:

Crie um novo banco de dados SQLite chamado empresa.db.

Conecte-se a ele e verifique se a conexão foi bem concluída.

Criação de tabela (DDL):

Crie uma tabela chamada funcionários com as seguintes colunas: id(INTEGER, chave primária, incremento automático) nome(TEXTO, não nulo) cargo(TEXTO, não nulo) salario(REAL) data_contratacao(TEXTO, não nulo)

Verificação da estrutura da tabela: Escreva um comando para obter a estrutura da tabela funcionários e exiba-a para confirmar se as colunas foram criadas corretamente.

In [81]:
#conn.commit()
#cursor.close()

In [82]:
#1
import sqlite3
import pandas as pd

database_name = "empresa__zika_memo_company_3.db"
conn = sqlite3.connect(database_name, timeout=10.0)
cursor = conn.cursor()

table_name_employee = "Employees"
table_name_department = "Departments"

create_table_employee = f"""
CREATE TABLE IF NOT EXISTS {table_name_employee} (
  id INTEGER  PRIMARY KEY,
  name        TEXT,
  position    TEXT,
  income      REAL
);
"""

def check_connection(conn):
  try:
    conn.cursor()
    return 'Online' if True else 'Offline'
  except Exception as ex:
    return 'Offline'

print("Database Name:", database_name)
print("Connection Status:", check_connection(conn))
print("")

cursor.execute(create_table_employee)

cursor.execute(f"PRAGMA table_info({table_name_employee})")
columns = cursor.fetchall()

for i in columns:
  print("Column Name:", i[1].upper(), "- Column Type:", i[2])

Database Name: empresa__zika_memo_company_3.db
Connection Status: Online

Column Name: ID - Column Type: INTEGER
Column Name: NAME - Column Type: TEXT
Column Name: POSITION - Column Type: TEXT
Column Name: INCOME - Column Type: REAL

In [83]:
#cursor.execute(f"DELETE FROM {table_name_employee}")

#Parte 2: Manipulação de Dados (DML)

Inserção de dados (INSERT): Insira pelo menos 5 registros na tabela funcionários com dados fictícios.

Consulta de dados (SELECT): Escreva um comando SELECT para exibir todos os registros da tabela funcionários.

Filtro com WHERE:

Selecione apenas os funcionários com salário superior a R$ 5.000. Selecione os funcionários que trabalham como 'Gerente'.

Atualização de dados (UPDATE): Atualizar o salário de um funcionário específico. Por exemplo, aumentar o salário de ‘João’ em 10%.

Exclusão de dados (DELETE): Exclui um dos funcionários que você inseriu.

Contagem de registros: Conte o número total de funcionários na tabela.

In [84]:
#Insert

excel_employees = {
    "name": ["Julia Vilela", "Salcy Lima", "Aline Midlej", "Marina Demori", "Gabriela Dias"],
    "position": ["Reporter", "Jornalist", "Presenter", "Director", "Presenter"],
    "income": [35000.00, 1000.00, 89000.90, 89900.00, 4000.00]
}

df = pd.DataFrame(excel_employees)

for _, row in df.iterrows():
  cursor.execute(f"""
    INSERT INTO {table_name_employee}
      (name, position, income)
    VALUES (?, ?, ?)
  """, (row["name"], row["position"], row["income"]))

conn.commit()

cursor.execute(f"""
                SELECT
                  *
                FROM {table_name_employee};
              """)
display(pd.DataFrame(cursor.fetchall(), columns = ["id", "name", "position", "income"]))
print("--")

cursor.execute(f"""
                SELECT
                  *
                FROM {table_name_employee}
                WHERE
                  income > 5000;
              """)

display(pd.DataFrame(cursor.fetchall(), columns = ["id", "name", "position", "income"]))
print("--")

cursor.execute(f"""
              UPDATE {table_name_employee}
              SET income = income + (income * 0.1)
              WHERE name = 'Salcy Lima'
              """)
conn.commit()

cursor.execute(f"""
                DELETE FROM {table_name_employee}
                WHERE name = 'Julia Vilela';
              """)
conn.commit()

cursor.execute(f"""
                SELECT
                  COUNT(*)
                FROM {table_name_employee}""")

print("TOTAL Employees: ", cursor.fetchone())

   id           name   position   income
0   1   Julia Vilela   Reporter  35000.0
1   2     Salcy Lima  Jornalist   1000.0
2   3   Aline Midlej  Presenter  89000.9
3   4  Marina Demori   Director  89900.0
4   5  Gabriela Dias  Presenter   4000.0

--

   id           name   position   income
0   1   Julia Vilela   Reporter  35000.0
1   3   Aline Midlej  Presenter  89000.9
2   4  Marina Demori   Director  89900.0

--
TOTAL Employees:  (4,)

##Parte 3: Agregação e Ordenação


Funções
de agregação ( SUM, AVG, MAX, MIN):

Calcule a soma total dos salários.

Calcule o salário médio da empresa.

Encontre o salário mais alto e o mais baixo.

Agrupamento de dados ( GROUP BY):

Calcule um salário médio para cada cargo.

Conte quantos funcionários existem em cada carga.

Ordenação
( ORDER BY):

Selecione todos os funcionários e ordens de maior para o menor salário.

Selecione todos os funcionários e ordene-os por nome em ordem alfabética.

In [85]:
#3

cursor.execute(f"""
                SELECT
                  SUM(income)
                  FROM {table_name_employee}""")
print("Total Income:", cursor.fetchone())

cursor.execute(f"""
                SELECT
                  AVG(income)
                  FROM {table_name_employee}""")
print("Average Income:", cursor.fetchone())

cursor.execute(f"""
                SELECT
                  MAX(income)
                  FROM {table_name_employee}""")
print("Bigger Income:", cursor.fetchone())

cursor.execute(f"""
                SELECT
                  MIN(income)
                  FROM {table_name_employee}""")
print("Smaller Income:", cursor.fetchone())

cursor.execute(f"""
                SELECT
                  position,
                  AVG(income)
                  FROM {table_name_employee}
                  GROUP BY position
                  ORDER BY position
               """)
display(pd.DataFrame(cursor.fetchall(), columns = ["position", "income"]))

cursor.execute(f"""
                SELECT
                  position,
                  COUNT(income)
                  FROM {table_name_employee}
                  GROUP BY position
                  ORDER BY position
               """)
display(pd.DataFrame(cursor.fetchall(), columns = ["position", "income"]))

cursor.execute(f"""
                SELECT
                  *
                  FROM {table_name_employee}
                  ORDER BY income DESC
               """)
display(pd.DataFrame(cursor.fetchall(), columns = ["id", "name", "position", "income"]))

select_all_employees = f"""
                SELECT
                  *
                  FROM {table_name_employee}
                  ORDER BY name
               """
cursor.execute(select_all_employees)
display(pd.DataFrame(cursor.fetchall(), columns = ["id", "name", "position", "income"]))

Total Income: (184000.9,)
Average Income: (46000.225,)
Bigger Income: (89900.0,)
Smaller Income: (1100.0,)

    position    income
0   Director  89900.00
1  Jornalist   1100.00
2  Presenter  46500.45

    position  income
0   Director       1
1  Jornalist       1
2  Presenter       2

   id           name   position   income
0   4  Marina Demori   Director  89900.0
1   3   Aline Midlej  Presenter  89000.9
2   5  Gabriela Dias  Presenter   4000.0
3   2     Salcy Lima  Jornalist   1100.0

   id           name   position   income
0   3   Aline Midlej  Presenter  89000.9
1   5  Gabriela Dias  Presenter   4000.0
2   4  Marina Demori   Director  89900.0
3   2     Salcy Lima  Jornalist   1100.0

##Parte 4: Transações e ROLLBACK


Simulação de transação:

Iniciar uma transação.

Insira um novo funcionário na tabela.

Simule um erro (por exemplo, dividindo por zero ou forçando um erro) para
acionar o except.

Utilize conn.rollback() para reverter a transação e garantir que o novo
funcionário não seja salvo no banco de dados.

Transação com COMMIT:

Inicie uma nova transação.

Insira um novo funcionário.

Não force o erro e use conn.commit() para salvar a operação permanentemente.
Verifique se o novo funcionário agora faz parte da tabela.

In [86]:
#4
try:
    conn.execute("BEGIN;")

    cursor.execute(f"""
      INSERT INTO {table_name_employee}
        (
          name,
          position,
          income
        )
        VALUES
        (
          'Indianara Campos',
          'Reporter'
          20000
        )
    """)

    conn.commit()
except Exception as e:
    conn.rollback()
    print("Error! The command did not run succesfully. Detail:", e)

Error! The command did not run succesfully. Detail: near "20000": syntax error

In [87]:
try:
    conn.execute("BEGIN;")

    cursor.execute(f"""
      INSERT INTO {table_name_employee}
        (
          name,
          position,
          income
        )
        VALUES
        (
          'Indianara Campos',
          'Reporter',
          20000
        )
    """)

    conn.commit()
except Exception as e:
    conn.rollback()
    print("Error! The command did not run succesfully. Detail:", e)


cursor.execute(select_all_employees)
display(pd.DataFrame(cursor.fetchall(), columns = ["id", "name", "position", "income"]))

   id              name   position   income
0   3      Aline Midlej  Presenter  89000.9
1   5     Gabriela Dias  Presenter   4000.0
2   6  Indianara Campos   Reporter  20000.0
3   4     Marina Demori   Director  89900.0
4   2        Salcy Lima  Jornalist   1100.0

##Parte 5: Joins e Múltiplas Tabelas


Criação de uma segunda tabela:

Crie uma nova tabela chamada departamentos com as colunas:
id(INTEGER,
chave primária, incremento automático)
nome_departamento(TEXTO, não nulo)
localizacao(TEXTO)

Insira pelo menos 3 departamentos.

Adição de chave estrangeira (ALTER TABLE):

Use ALTER TABLE para adicionar uma nova coluna departamento_id na tabela funcionarios.

Esta coluna deve ser uma chave estrangeira que se refere id à tabela
departamentos.

Atualização de dados:

Atualize uma tabela funcionarios para fornecer departamento_id a cada funcionário, conectando-os aos departamentos que você criou.

INNER JOIN:
Crie uma consulta que combine as tabelas funcionarios e departamentos para exibir o nome de cada funcionário junto com o nome do seu departamento.

LEFT JOIN:
Crie uma nova tabela chamada projetos com as colunas id e nome_projeto.


Crie uma tabela de particular funcionarios_projetos com funcionario_id e projeto_id para representar a relação de N para N.

Use um LEFT JOIN para listar todos os funcionários e, se houver, o nome do
projeto em que estão.

In [88]:
#5
#conn.commit()
create_table_departments = f"""
CREATE TABLE IF NOT EXISTS {table_name_department} (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  name_department   TEXT NOT NULL,
  localization      TEXT
);
"""
cursor.execute(create_table_departments)

cursor.execute(f"PRAGMA table_info({table_name_department})")
columns = cursor.fetchall()

for i in columns:
  print("Column Name:", i[1].upper(), "- Column Type:", i[2])

alter_table_employees = f"""
  ALTER TABLE
    {table_name_employee}
  ADD COLUMN
    department_id INT
"""

cursor.execute(alter_table_employees)

Column Name: ID - Column Type: INTEGER
Column Name: NAME_DEPARTMENT - Column Type: TEXT
Column Name: LOCALIZATION - Column Type: TEXT

In [89]:
cursor.execute(f"PRAGMA table_info({table_name_employee})")
columns = cursor.fetchall()

for i in columns:
  print("Column Name:", i[1].upper(), "- Column Type:", i[2])

Column Name: ID - Column Type: INTEGER
Column Name: NAME - Column Type: TEXT
Column Name: POSITION - Column Type: TEXT
Column Name: INCOME - Column Type: REAL
Column Name: DEPARTMENT_ID - Column Type: INT

In [90]:
cursor.execute(select_all_employees)
display(pd.DataFrame(cursor.fetchall(), columns = ["id", "name", "position", "income", "department_id"]))

   id              name   position   income department_id
0   3      Aline Midlej  Presenter  89000.9          None
1   5     Gabriela Dias  Presenter   4000.0          None
2   6  Indianara Campos   Reporter  20000.0          None
3   4     Marina Demori   Director  89900.0          None
4   2        Salcy Lima  Jornalist   1100.0          None

In [91]:
cursor.execute(f"PRAGMA table_info({table_name_department})")
cursor.fetchall()

[(0, 'id', 'INTEGER', 0, None, 1),
 (1, 'name_department', 'TEXT', 1, None, 0),
 (2, 'localization', 'TEXT', 0, None, 0)]

In [92]:
excel_department = {
    "name": ["Youtube", "Spotify"],
    "position": ["Chácara Santo Antônio", "Av. Paulista"]
}

df = pd.DataFrame(excel_department)

for _, row in df.iterrows():
  cursor.execute(f"""
    INSERT INTO {table_name_department}
      (name_department, localization)
    VALUES (?, ?)
  """, (row["name"], row["position"]))

conn.commit()

In [93]:
update_table_employess = f"""
  UPDATE {table_name_employee}
  SET department_id = 3
  WHERE id = 4
"""
cursor.execute(update_table_employess)
conn.commit()

In [94]:
cursor.execute(f"SELECT * FROM {table_name_employee}")
cursor.fetchall()

[(2, 'Salcy Lima', 'Jornalist', 1100.0, None),
 (3, 'Aline Midlej', 'Presenter', 89000.9, None),
 (4, 'Marina Demori', 'Director', 89900.0, 3),
 (5, 'Gabriela Dias', 'Presenter', 4000.0, None),
 (6, 'Indianara Campos', 'Reporter', 20000.0, None)]

In [95]:
cursor.execute(f"SELECT * FROM {table_name_department}")
cursor.fetchall()

[(1, 'Youtube', 'Chácara Santo Antônio'), (2, 'Spotify', 'Av. Paulista')]

In [96]:
cursor.execute('''
SELECT
    employees.name,
    departments.name_department
FROM employees
INNER JOIN departments ON employees.department_id = departments.id;
''')

for row in cursor.fetchall():
    print(f"Name: {row[0]}")
    print(f"Department: {row[1]}")
    print()

In [97]:
create_table_projects = f"""
CREATE TABLE IF NOT EXISTS projects (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  name_project      TEXT NOT NULL
);
"""
cursor.execute(create_table_projects)

cursor.execute(f"PRAGMA table_info(projects)")
cursor.fetchall()

[(0, 'id', 'INTEGER', 0, None, 1), (1, 'name_project', 'TEXT', 1, None, 0)]

In [98]:
create_table_employees_projects = f"""
CREATE TABLE IF NOT EXISTS employees_projects (
  employee_id     INTEGER,
  project_id      INTEGER
);
"""
cursor.execute(create_table_employees_projects)

cursor.execute(f"PRAGMA table_info(employees_projects)")
cursor.fetchall()

[(0, 'employee_id', 'INTEGER', 0, None, 0),
 (1, 'project_id', 'INTEGER', 0, None, 0)]

In [99]:
cursor.execute(f"SELECT * FROM employees")
cursor.fetchall()

[(2, 'Salcy Lima', 'Jornalist', 1100.0, None),
 (3, 'Aline Midlej', 'Presenter', 89000.9, None),
 (4, 'Marina Demori', 'Director', 89900.0, 3),
 (5, 'Gabriela Dias', 'Presenter', 4000.0, None),
 (6, 'Indianara Campos', 'Reporter', 20000.0, None)]

In [100]:
cursor.execute("INSERT INTO projects (name_project) VALUES ('Vida Drama')")
cursor.execute("INSERT INTO projects (name_project) VALUES ('Thug Life')")

In [101]:
cursor.execute(f"SELECT * FROM projects")
cursor.fetchall()

[(1, 'Vida Drama'), (2, 'Thug Life')]

In [109]:

cursor.execute(f"""
                DELETE FROM employees_projects;
              """)
conn.commit()

In [111]:
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (6,1)")
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (6,2)")
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (2,1)")
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (3,1)")
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (4,1)")
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (4,2)")
cursor.execute("INSERT INTO employees_projects (employee_id, project_id) VALUES (5,1)")
conn.commit()

In [112]:
cursor.execute(f"SELECT * FROM employees_projects")
cursor.fetchall()

[(6, 1), (6, 2), (2, 1), (3, 1), (4, 1), (4, 2), (5, 1)]

In [113]:
cursor.execute('''
SELECT
    employees.name,
    projects.name_project
FROM employees
LEFT JOIN employees_projects ON employees.id = employees_projects.employee_id
JOIN projects ON projects.id = employees_projects.project_id = projects.id;
''')

for row in cursor.fetchall():
    print(f"Name: {row[0]}")
    print(f"Project: {row[1]}")
    print()

Name: Indianara Campos
Project: Vida Drama

Name: Salcy Lima
Project: Vida Drama

Name: Aline Midlej
Project: Vida Drama

Name: Marina Demori
Project: Vida Drama

Name: Gabriela Dias
Project: Vida Drama

In [114]:
conn.commit()
conn.close()

##Parte 6: DCL (Controle de Dados)


Conceito de DCL:
No seu notebook, explique em markdown a diferença entre DDL, DML, DQL e DCL,
focando em para que o DCL seja usado.

Após concluir todos os exercícios, lembre-se de encerrar a conexão com o banco de dados.

In [ ]:
#DDL - Data Definition Language - Usada para criar físicamente o que quer no banco.
#     Definir estrutura

#DML - Data Manipulation Language - Usada para utilizar os dados na estrutura criada previamente,
#     Manipular o banco

#DQL - Data Querying Language - Usada para visualizar os dados. Manipular comandos para trazer os dados da forma desejada

#DCL - Data Control Language - Usada para manipulação de transações e afins. Maneira mais profissional de 'DMLa' no banco